#@TODO The following welcome section will be removed when we have portal as index.
#All controllers under market need to be push into /market/ 
welcome:
    pattern:  /
    defaults: { _controller: YunshangMarketBundle:Default:index }

YunshangCustomerBundle:
    resource: "@YunshangCustomerBundle/Controller/"
    type:     annotation
    prefix:   /customer/

YunshangMarketBundle:
    resource: "@YunshangMarketBundle/Controller/"
    type:     annotation
    prefix:   /market/

YunshangManageBundle:
    resource: "@YunshangManageBundle/Controller/"
    type:     annotation
    prefix:   /manage/

YunshangCommonBundle:
    resource: "@YunshangCommonBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
