security:
    encoders:
        Yunshang\Bundle\CommonBundle\Entity\Account\Member: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: {class:Yunshang\Bundle\CommonBundle\Entity\Account\Member,property:username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|static)/
            security: false

        login:
            pattern:  ^/account/login$
            security: false

        secured_area:
            pattern:    ^/*
            form_login:
                check_path: /account/login_check
                login_path: /account/login
            logout:
                path:   /account/logout
                target: /
            anonymous: true
        member_area:
            pattern:   ^/(account/*|customer/*)
            form_login:
                check_path: /account/login_check
                login_path: /account/login
            logout:
                path:   /account/logout
                target: /
            anonymous: false            
        manage_area:
            pattern:   ^/(account/*|manage/*)
            form_login:
                check_path: /account/login_check
                login_path: /account/login
            logout:
                path:   /account/logout
                target: /
            anonymous: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
