security:
    encoders:
        Yunshang\Bundle\CommonBundle\Entity\Account\Member: sha512

    role_hierarchy:
        ROLE_REGISTER:    ROLE_USER
        ROLE_MANAGER:     ROLE_REGISTER
        ROLE_ADMIN:       [ROLE_REGISTER,ROLE_USER,ROLE_MANAGER,ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: {class:Yunshang\Bundle\CommonBundle\Entity\Account\Member,property:username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|static)/
            security: false

        login:
            pattern:  ^/account/login$
            security: false

        yunshang_area:
            pattern:    ^/*
            form_login:
                check_path: /account/login_check
                login_path: /account/login
                always_use_default_target_path: false
                default_target_path: /
                target_path_parameter: _target_path
#                remember_me: true
            logout:
                path:   /account/logout
                target: /
            anonymous: true
#            remember_me:
#                key: sdkfhasiuyiuerhksdf
#                name: yunshang_rem_id_key
#                lifetime: 360000 # in seconds
#                path: /
#                secure: true
#                httponly: true
#                always_remember_me: false
#                remember_me_parameter: _remember_me

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer/*, roles: IS_AUTHENTICATED_MANAGER}
        - { path: ^/manager/*, roles: IS_AUTHENTICATED_MANAGER}
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
